name: ui_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  adobe_xd: ^0.1.0
  flutter_svg: ^0.17.4
  flutter_multiselect: ^0.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo1.png
    - images/icon.jpeg
    - images/057-upload.png
    - images/image1.jpg
    - images/image2.jpeg
    - images/image3.png
    - images/image4.png
    - images/zakat1.jpg
    - images/zakat2.jpg
    - images/zakat3.jpg
    - images/zakat4.jpg
    - images/zakat5.jpg
    - images/zakat6.jpg
    - images/zakat7.jpg
    - images/zakat8.jpg
    - images/da3m1.png
    - images/da3m2.jpg
    - images/da3m3.png
    - images/da3m4.jpg
    - images/da3m5.png
    - images/da3m6.png
    - images/da3m7.png
    - images/da3m8.png
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/7.jpg
    - images/8.jpg
    - images/9.jpg
    - images/10.png
    - images/111.jpeg
    - images/12.png
    - images/643.jpg
    - images/15.jpg
    - images/22.png
    - images/23.jpg
    - images/24.jpg
    - images/tnmya1.jpg
    - images/tnmya2.png
    - images/tnmya3.jpg
    - images/charity.png
    - images/upload.png
    - images/case.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Simple
    fonts:
     - asset: fonts/Simple.ttf
  - family: Century
    fonts:
    - asset: fonts/CenturyGothic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
